    # The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
    modLoader="javafml"
    # A version range to match for said mod loader - for regular FML @Mod it will be the forge version
    # Forge for 1.15.2 is version 31
    loaderVersion="[34,)"
    # A URL to refer people to when problems occur with this mod
    issueTrackerURL="https://github.com/MinecraftForge/MinecraftForge/issues"
    # If the mods defined in this file should show as seperate resource packs
    showAsResourcePack=false
    license="All Rights Reserved"

    [[mods]]
      modId="stopsellingenchants"
      version="1.0.0.0"
      displayName="Stop Selling Enchants"
      updateJSONURL="https://minecraftforge.net/versions.json"
      displayURL="https://minecraftforge.net"
      logoFile="assets/examplemod/textures/logo.png"
      credits="I'd like to thank my mother and father."
      authors="Author"
      description='''
      Everything was well balanced in my modpack until they build the trading jail.
      '''

      [[dependencies.examplemod]]
        modId="forge"
        mandatory=true
        versionRange="[34,)"
        ordering="NONE"
        side="BOTH"

      [[dependencies.examplemod]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.16.3]"
        ordering="NONE"
        side="BOTH"